### ISSUE TITLE
No module named 'code.env'

### ISSUE THREAD

**Issue by mao-xu** [microsoft/EPPO#3]
When we run python code/tools/train_on_atari.py exp/atari_local.yml， we get the following error：
Traceback (most recent call last):
  File "code/tools/train_on_atari.py", line 25, in <module>
    from code.env import EnvConfig
ModuleNotFoundError: No module named 'code.env'

We searched the folder code and did not find the file env. Maybe, the file env is forgotten to put into the folder code.

**Comment by rk2900** [comment]
> When we run python code/tools/train_on_atari.py exp/atari_local.yml， we get the following error： Traceback (most recent call last): File "code/tools/train_on_atari.py", line 25, in from code.env import EnvConfig ModuleNotFoundError: No module named 'code.env'
> 
> We searched the folder code and did not find the file env. Maybe, the file env is forgotten to put into the folder code.

Hi there, sorry for the inconvenience. We've checked with the file list and found some code files were ignored following the git ignore rules. Now we've updated the repository and hope you can find it helpful.

Thank you for your report.

**Comment by mao-xu** [comment]
Thank you， I have run python code/tools/train_on_atari.py exp/atari_local.yml successfully.
